import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/ja/',
          '/en/',
          '/zh/',
          '/ko/',
          '/es/',
          '/fr/',
          '/de/',
          '/ja/directory',
          '/en/directory',
          '/zh/directory',
          '/ko/directory',
          '/es/directory',
          '/fr/directory',
          '/de/directory',
          '/ja/search',
          '/en/search',
          '/zh/search',
          '/ko/search',
          '/es/search',
          '/fr/search',
          '/de/search',
          '/ja/o/',
          '/en/o/',
          '/zh/o/',
          '/ko/o/',
          '/es/o/',
          '/fr/o/',
          '/de/o/',
          '/ja/api/docs',
          '/en/api/docs',
          '/zh/api/docs',
          '/ko/api/docs',
          '/es/api/docs',
          '/fr/api/docs',
          '/de/api/docs',
        ],
        disallow: [
          '/api/auth/',
          '/admin/',
          '/dashboard/settings/',
          '/_next/',
          '/private/',
          '*.pdf$',
          '*/temp/*',
          '/ja/dashboard/settings/',
          '/en/dashboard/settings/',
          '/zh/dashboard/settings/',
          '/ko/dashboard/settings/',
          '/es/dashboard/settings/',
          '/fr/dashboard/settings/',
          '/de/dashboard/settings/',
        ],
      },
      {
        userAgent: 'GPTBot',
        disallow: '/',
      },
      {
        userAgent: 'ChatGPT-User',
        disallow: '/',
      },
      {
        userAgent: 'CCBot',
        disallow: '/',
      }
    ],
    sitemap: `${process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3001'}/sitemap.xml`,
    host: process.env.NEXT_PUBLIC_SITE_URL ?? 'http://localhost:3001',
  }
}